# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{marlene}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Duerr"]
  s.date = %q{2010-07-09}
  s.description = %q{Marlene generates bookmarklet files or bookmarklet-pages from existing local javascript files or from remote javascript files represented by a URL.}
  s.email = %q{thomduerr@gmail.com}
  s.executables = ["bm.pl", "marlene"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "bin/marlene",
     "lib/marlene.rb",
     "lib/templates/loader.js",
     "lib/templates/page.html",
     "spec/marlene_spec.rb"
  ]
  s.homepage = %q{http://github.com/thomd/marlene/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Bookmarklet Generator from a local or remote JavaScript file}
  s.test_files = [
    "spec/marlene_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yui-compressor>, [">= 0.9.1"])
      s.add_runtime_dependency(%q<mustache>, [">= 0.11.2"])
    else
      s.add_dependency(%q<yui-compressor>, [">= 0.9.1"])
      s.add_dependency(%q<mustache>, [">= 0.11.2"])
    end
  else
    s.add_dependency(%q<yui-compressor>, [">= 0.9.1"])
    s.add_dependency(%q<mustache>, [">= 0.11.2"])
  end
end

